### ISSUE TITLE
Add command to retrieve LXD_DIR or lxd socket path

### ISSUE THREAD

**Issue by sergiusens** [lxc/lxd-pkg-snap#33]
A way to use pylxd without the magic of guessing or hardcoding would be nice, here are some random thoughts on how to get there:

- something to print out the socket to pass as the endpoint https://github.com/lxc/pylxd/blob/master/pylxd/client.py#L257
- a way to retrieve/echo `LXD_DIR` from the snap https://github.com/lxc/pylxd/blob/master/pylxd/client.py#L287

I do not want to consider /var/snap/lxd/common/lxd/unix.socket as a stable path (https://github.com/lxc/pylxd/blob/master/pylxd/client.py#L292) even if, so far it has been stable since its inception.

**Comment by stgraber** [comment]
Hmm, we don't intend to expose a subcommand solely for the purpose of getting LXD_DIR from the snap.
So that leaves you with two options:
 - Hardcode `/var/snap/lxd/common/lxd/unix.socket` which is what we've done everywhere so far as an alternative to the previously hardcoded `/var/lib/lxd/unix.socket`
 - Determine what SNAP_COMMON is for yourself and then look for `lxd/unix.socket` in there
 - Assume that we use socket activation, track down the systemd unit and get the path from that

The only thing I could see us doing is putting a file in /var/snap/lxd/common which includes the LXD_DIR environment there, but that seems a bit pointless given that you'll already need to hardcode /var/snap/lxd/common just to be told that LXD_DIR is always the `lxd` directory in there.

**Comment by sergiusens** [comment]
I was just looking at lxd.migrate as I received the email notification for your response and also saw https://github.com/lxc/lxd-pkg-snap/blob/latest-edge/lxd-migrate/main.go#L57 so I guess things are pretty tied together.

For the purposes of snapcraft, which runs outside the "base" I will resort as a workaround (until snapd offers a way to expose these variable paths) to infer the socket path using SNAP_COMMON from snapcraft.

Feel free to close this

**Comment by stgraber** [comment]
@sergiusens yeah and I believe nova-lxd effectively looks for /var/snap/lxd/common/lxd, if it exists, it uses that through pylxd, if not, it just moves on to assuming /var/lib/lxd
