### ISSUE TITLE
LXD 3.20 restart's in endless loop

### ISSUE THREAD

**Issue by rigred** [lxc/lxd-pkg-snap#50]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04.3 LTS
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.0.0-31-generic lxc/lxd#33~18.04.1-Ubuntu SMP
   * LXC version: 3.20
   * LXD version: 3.20
   * Storage backend in use: ZFS

# Issue description

This issue seems to have begun on January 23rd during an automatic snap refresh when a storage-pool mount move failed, then went unnoticed by me while I was away. The containers themselves are unaffected and keep running but the lxd control is lost. All lxc commands are non responsive and get stuck.

It began with the following message:
```
Jan 23 16:53:14 hetz-hel6 lxd.daemon[30985]: Failed to move mount '/var/snap/lxd/common/lxd/storage-pools/local/images/510081712' to '/var/snap/lxd/common/shmounts/storage-pools/local/images/510081712: Invalid argument
```
I suspect that issue [#6835](https://github.com/lxc/lxd/issues/6835) might be related.

# Steps to reproduce

 1. I have no idea, this was a fully automated failure essentially.

# Information to attach

[hetz-hel6_journal_logs_16-53.log](https://github.com/lxc/lxd/files/4159418/hetz-hel6_journal_logs_16-53.log)

[hetz-hel6_lxd_direct.log](https://github.com/lxc/lxd/files/4159414/hetz-hel6_lxd_direct.log)

[hetz-hel6_lxd_restart.log](https://github.com/lxc/lxd/files/4159402/hetz-hel6_lxd_restart.log)

**Comment by rigred** [comment]
### nsenter --mount=/run/snapd/ns/lxd.mnt cat /proc/self/mountinfo
[mountinfo.txt](https://github.com/lxc/lxd-pkg-snap/files/4159961/mountinfo.txt)

### nsenter --mount=/run/snapd/ns/lxd.mnt ls -lh /var/snap/lxd/common/lxd/images/
```
total 95M
-rw-r--r-- 1 root root 780 Jan 15 17:50 229de7a9ac232619fbe7e85ee235e97d94b9cb75aca3e059f451c9d684381144
-rw-r--r-- 1 root root 95M Jan 15 17:50 229de7a9ac232619fbe7e85ee235e97d94b9cb75aca3e059f451c9d684381144.rootfs
```
### nsenter --mount=/run/snapd/ns/lxd.mnt ls -lh /var/snap/lxd/common/lxd/storage-pools/local/images/
```
total 2.5K
drwx------ 2 root root 2 Oct  8 23:37 208d20a60acbdc1e76eb384900d2b03c1857002c3c89d7581eab07a1fdd2f799
drwx------ 2 root root 2 Jan 15 17:50 229de7a9ac232619fbe7e85ee235e97d94b9cb75aca3e059f451c9d684381144
drwxr-xr-x 4 root root 5 Oct  8 23:37 510081712
drwx------ 2 root root 2 Sep 27 10:26 792148226
drwx------ 2 root root 2 Sep 27 10:15 982872339
```

**Comment by stgraber** [comment]
Oh wow, that mount table really isn't looking too good.

Anyway, lets cleanup things a bit with:
 - nsenter --mount=/run/snapd/ns/lxd.mnt umount -l /var/snap/lxd/common/lxd/storage-pools/local/images/510081712
 - nsenter --mount=/run/snapd/ns/lxd.mnt umount -l /var/snap/lxd/common/lxd/storage-pools/local/images/792148226
 - nsenter --mount=/run/snapd/ns/lxd.mnt umount -l /var/snap/lxd/common/lxd/storage-pools/local/images/982872339
 - nsenter --mount=/run/snapd/ns/lxd.mnt umount -l /var/snap/lxd/common/lxd/storage-pools/local/images/208d20a60acbdc1e76eb384900d2b03c1857002c3c89d7581eab07a1fdd2f799
 - nsenter --mount=/run/snapd/ns/lxd.mnt rmdir /var/snap/lxd/common/lxd/storage-pools/local/images/510081712
 - nsenter --mount=/run/snapd/ns/lxd.mnt rmdir /var/snap/lxd/common/lxd/storage-pools/local/images/792148226
 - nsenter --mount=/run/snapd/ns/lxd.mnt rmdir /var/snap/lxd/common/lxd/storage-pools/local/images/982872339
 - nsenter --mount=/run/snapd/ns/lxd.mnt rmdir /var/snap/lxd/common/lxd/storage-pools/local/images/208d20a60acbdc1e76eb384900d2b03c1857002c3c89d7581eab07a1fdd2f799

I expect most of the `umount` calls to fail, that's fine. The rmdir should succeed and that will cleanup those invalid entries.

After that, if it's an option, I'd recommend you reboot the system, that will clear all the duplicate entries in that mount table. It will also get your kernel onto 5.0.0-38 rather than 5.0.0-31 that you're currently running (you're 7 security/bugfix updates behind).

If that's not an option, there's still a good chance that LXD will now start fine, but the heavily polluted mount table will likely come at a performance cost for anything dealing with mounts on the system, so I'd still strongly recommend rebooting when convenient (not to mention the kernel updates).

**Comment by rigred** [comment]
That did not go too well. 

While I did reboot the system and fix the mounts issue, I cannot start lxd again, neither in the snap nor directly. It just segfaults.


```
admin@hetz-hel6:~$ sudo lxd --debug --group lxd
INFO[02-06|00:23:46] LXD 3.20 is starting in normal mode      path=/var/snap/lxd/common/lxd
INFO[02-06|00:23:46] Kernel uid/gid map: 
INFO[02-06|00:23:46]  - u 0 0 4294967295 
INFO[02-06|00:23:46]  - g 0 0 4294967295 
INFO[02-06|00:23:46] Configured LXD uid/gid map: 
INFO[02-06|00:23:46]  - u 0 1000000 1000000000 
INFO[02-06|00:23:46]  - g 0 1000000 1000000000 
INFO[02-06|00:23:46] Kernel features: 
INFO[02-06|00:23:46]  - netnsid-based network retrieval: yes 
INFO[02-06|00:23:46]  - uevent injection: yes 
INFO[02-06|00:23:46]  - seccomp listener: yes 
INFO[02-06|00:23:46]  - seccomp listener continue syscalls: yes 
INFO[02-06|00:23:46]  - unprivileged file capabilities: yes 
INFO[02-06|00:23:46]  - cgroup layout: hybrid 
WARN[02-06|00:23:46]  - Couldn't find the CGroup blkio.weight, I/O weight limits will be ignored 
WARN[02-06|00:23:46]  - Couldn't find the CGroup memory swap accounting, swap limits will be ignored 
INFO[02-06|00:23:46]  - shiftfs support: yes 
INFO[02-06|00:23:46] Initializing local database 
DBUG[02-06|00:23:46] Initializing database gateway 
DBUG[02-06|00:23:46] Start database node                      id=1 address=95.216.Y.XXX:8443 role=voter
INFO[02-06|00:23:46] Starting /dev/lxd handler: 
INFO[02-06|00:23:46]  - binding devlxd socket                 socket=/var/snap/lxd/common/lxd/devlxd/sock
INFO[02-06|00:23:46] REST API daemon: 
INFO[02-06|00:23:46]  - binding Unix socket                   socket=/var/snap/lxd/common/lxd/unix.socket
INFO[02-06|00:23:46]  - binding TCP socket                    socket=95.216.Y.XXX:8443
INFO[02-06|00:23:46] Initializing global database 
DBUG[02-06|00:23:46] Found cert                               name=0
DBUG[02-06|00:23:46] Found cert                               name=0
DBUG[02-06|00:23:46] Dqlite: connected address=95.216.Y.XXX:8443 id=1 attempt=0 
WARN[02-06|00:23:51] Dqlite client proxy TLS -> Unix: read tcp 95.216.Y.XXX:39808->95.216.Y.XXX:8443: use of closed network connection 
WARN[02-06|00:23:51] Dqlite server proxy Unix -> TLS: read unix @->@00219: use of closed network connection 
DBUG[02-06|00:23:52] Found cert                               name=0
DBUG[02-06|00:23:52] Found cert                               name=0
DBUG[02-06|00:23:52] Dqlite: connected address=95.216.Y.XXX:8443 id=1 attempt=0 
WARN[02-06|00:23:57] Dqlite client proxy TLS -> Unix: read tcp 95.216.Y.XXX:39812->95.216.Y.XXX:8443: use of closed network connection 
WARN[02-06|00:23:57] Dqlite server proxy Unix -> TLS: read unix @->@00219: use of closed network connection 
DBUG[02-06|00:23:57] Found cert                               name=0
DBUG[02-06|00:23:57] Found cert                               name=0
DBUG[02-06|00:23:57] Dqlite: connected address=95.216.Y.XXX:8443 id=1 attempt=0 
EROR[02-06|00:24:02] Failed to start the daemon: failed to open cluster database: Failed to set page cache size: driver: bad connection 
INFO[02-06|00:24:02] Starting shutdown sequence 
INFO[02-06|00:24:02] Stopping REST API handler: 
INFO[02-06|00:24:02]  - closing socket                        socket=95.216.Y.XXX:8443
WARN[02-06|00:24:02] Dqlite client proxy TLS -> Unix: read tcp 95.216.Y.XXX:39816->95.216.Y.XXX:8443: use of closed network connection 
INFO[02-06|00:24:02]  - closing socket                        socket=/var/snap/lxd/common/lxd/unix.socket
WARN[02-06|00:24:02] Dqlite server proxy Unix -> TLS: read unix @->@00219: use of closed network connection 
INFO[02-06|00:24:02] Stopping /dev/lxd handler: 
INFO[02-06|00:24:02]  - closing socket                        socket=/var/snap/lxd/common/lxd/devlxd/sock
DBUG[02-06|00:24:02] Stop database gateway 
Segmentation fault
```

It stalls for quite some time before restarting

```
lxd.daemon[31569]: t=2020-02-06T00:29:46+0200 lvl=dbug msg="Dqlite: connected address=95.216.7.225:8443 id=1 attempt=0"
systemd[1]: snap.lxd.daemon.service: Main process exited, code=exited, status=1/FAILURE
 systemd[1]: snap.lxd.daemon.service: Failed with result 'exit-code'.

```

**Comment by rigred** [comment]
This thing is so dead I'm just going to rebuild it.

**Comment by stgraber** [comment]
@rigred logging suggests that clustering was enabled? What kind of cluster was that?
If you can grab a dump of `/var/snap/lxd/common/lxd/database`, that may be useful to look into particular issues.
